<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>r6bot_gazebo</name>
  <version>1.0.0</version>
  <description>Pacote para simulação do manipulador R6bot no Gazebo para realização do hands on I e II</description>
  <maintainer email="matheuz__@hotmail.com">matheus</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>r6bot_description</exec_depend>
  <exec_depend>r6bot_control</exec_depend>
  <exec_depend>ros_gz</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
