<?xml version="1.0"?>
<package format="3">
  <name>kuka_gain_analysis</name>
  <version>0.1.0</version>
  <description>
    Obj. 2 — Estimar a influência das variações nos ganhos e no tipo de controle
    sobre a estabilidade e o desempenho do sistema. Varrimento de ganhos Kp/Kd,
    análise de estabilidade e geração de relatórios.
  </description>
  <maintainer email="matheuz__@hotmail.com">user</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>