controller_manager:
  ros__parameters:
    update_rate: 50  # deve ser igual ao do r6bot_controllers.yaml

    gripper_controller:
      type: r6bot_gripper/GripperController

gripper_controller:
  ros__parameters:
    ball_radius:  0.12
    min_position: 0.01
    max_position: 0.14
    joints:
      - gripper_finger_left_joint
      - gripper_finger_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort